name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action

      - name: Build and push
        uses: docker/build-push-action
        with:
          context: .
          file: ./Dockerfile
          push: false
